### PR TITLE
fixing: ts-sdk records keploy-testcase even on test mode 

### PR DESCRIPTION
**Pull request by Sekhar-Kumar-Dash**
this PR  closes: https://github.com/keploy/keploy/issues/430

### CODE REVIEW

**Comment by Sekhar-Kumar-Dash** [comment]
@re-Tick Please review this PR

**Comment by re-Tick** [comment]
This expression should also check for the empty KEPLOY_TEST_ID from the headers. Since, during the simulate request of test mode, the KEPLOY_TEST_ID is used for check.

Also there should be check in the afterMiddleware function also which will just return the response instead of recording it.

**Comment by Sekhar-Kumar-Dash** [comment]
@re-Tick  please check the it again

**Comment by re-Tick** [comment]
Please add the if check in afterMiddleware also after [this](https://github.com/keploy/typescript-sdk/blob/c47a2707376f65861d041e33aae55c77027b634b/integrations/express/middleware.ts#L139) "if check"

**Comment by re-Tick** [comment]
LGTM.

**Pull request merged**
